"""Init

Revision ID: 1ab28272caaa
Revises: 
Create Date: 2022-12-11 16:33:51.944692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab28272caaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('wear_time', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overalls_id'), 'overalls', ['id'], unique=False)
    op.create_index(op.f('ix_overalls_kind'), 'overalls', ['kind'], unique=False)
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshops_full_name'), 'workshops', ['full_name'], unique=False)
    op.create_index(op.f('ix_workshops_id'), 'workshops', ['id'], unique=False)
    op.create_index(op.f('ix_workshops_name'), 'workshops', ['name'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_full_name'), 'workers', ['full_name'], unique=False)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_table('recivings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('overall_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['overall_id'], ['overalls.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recivings_id'), 'recivings', ['id'], unique=False)
    op.create_index(op.f('ix_recivings_signature'), 'recivings', ['signature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recivings_signature'), table_name='recivings')
    op.drop_index(op.f('ix_recivings_id'), table_name='recivings')
    op.drop_table('recivings')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_full_name'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_workshops_name'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_id'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_full_name'), table_name='workshops')
    op.drop_table('workshops')
    op.drop_index(op.f('ix_overalls_kind'), table_name='overalls')
    op.drop_index(op.f('ix_overalls_id'), table_name='overalls')
    op.drop_table('overalls')
    # ### end Alembic commands ###
